// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityProgect.DataModel;

namespace UniversityProgect.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20220201103550_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("UniversityProgect.DataModel.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("COURSE_ID");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(300)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(25)")
                        .HasColumnName("NAME");

                    b.HasKey("CourseId");

                    b.ToTable("COURSES");
                });

            modelBuilder.Entity("UniversityProgect.DataModel.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    b.Property<long?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("COURSE_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("NAME");

                    b.HasKey("GroupId");

                    b.HasIndex("CourseId");

                    b.ToTable("GROUPS");
                });

            modelBuilder.Entity("UniversityProgect.DataModel.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("STUDENT_ID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<long?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LAST_NAME");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.ToTable("STUDENTS");
                });

            modelBuilder.Entity("UniversityProgect.DataModel.Group", b =>
                {
                    b.HasOne("UniversityProgect.DataModel.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("UniversityProgect.DataModel.Student", b =>
                {
                    b.HasOne("UniversityProgect.DataModel.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UniversityProgect.DataModel.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("UniversityProgect.DataModel.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
